name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:


jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        uses: ikmdev/maven-pull-request-version-validation-action@v1.0.0
        
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Artifact ID Property
        id: artifact_id_property
        run: |
          find . -name "pom.xml" -exec sh -c '
          for pom; do
            echo "Processing $pom"
            value=$(mvn help:evaluate -Dexpression=data-artifact.artifactId -q -DforceStdout -f "$pom")
            if [ -n "$value" ]; then
              echo "Value of data-artifact.artifactId in $pom: $value"
            else
              echo "Property data-artifact.artifactId not found in $pom"
            fi
          done
          ' sh {} +
          exit 1
      
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@v3.2.0
        with:
          branch_name: ${{github.ref_name}}
